# Generated by Django 3.1.2 on 2020-12-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('iddisease', models.IntegerField(db_column='idDisease', primary_key=True, serialize=False)),
                ('diseasename', models.CharField(blank=True, db_column='diseaseName', max_length=200, null=True)),
                ('prevalence', models.CharField(blank=True, db_column='Prevalence', max_length=30, null=True)),
                ('affectedsystem', models.CharField(blank=True, db_column='AffectedSystem', max_length=30, null=True)),
                ('treatment', models.CharField(blank=True, db_column='Treatment', max_length=100, null=True)),
                ('diagnosis', models.TextField(blank=True, db_column='Diagnosis', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'diseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('idresources', models.IntegerField(db_column='IdResources', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('finality', models.CharField(blank=True, db_column='Finality', max_length=20, null=True)),
                ('price', models.CharField(blank=True, db_column='Price', max_length=4, null=True)),
                ('access', models.CharField(blank=True, db_column='Access', max_length=7, null=True)),
            ],
            options={
                'db_table': 'resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourcesDiseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'resources_diseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourcesResourcestype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'resources_resourcestype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resourcestype',
            fields=[
                ('idtype', models.IntegerField(db_column='idType', primary_key=True, serialize=False)),
                ('Type', models.CharField(blank=True, db_column='Type', max_length=40, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'resourcestype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourcesUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'resources_url',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('idurl', models.IntegerField(db_column='idURL', primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, db_column='Language', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=300, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=60, null=True)),
            ],
            options={
                'db_table': 'url',
                'managed': False,
            },
        ),
    ]
