# Generated by Django 3.1.2 on 2020-12-30 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='url',
            table='urlTable',
        ),
    ]
