# Generated by Django 3.1.2 on 2020-12-30 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicesApp', '0002_auto_20201231_0030'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='url',
            table='url',
        ),
    ]
